package com.automation.baseframework;

/**
 * This class contain the enum all the keyword. 
 * @author Vinod Kumar R
 *
 */
public enum KeywordType {

  BANNER,
  BROWSERTYPE,
  BROWSERSWITCH,
  COMPETATIONFORM,
  MANDATORYQUESTION,
  MOBILEPARTICIPATE,
  CONSENT,
  CLOSEBROWSER,
  ENTEREMAILOTP,
  EMAILENCASH,
  ENCASHMENU,
  FIREBASELOGIN,
  FIREBASELOGIN1,
  GMAIL,
  GOTOLINK,
  JISHITEXT,
  LEVELS,
  LEVELTAB,
  LOGOUTADMIN,
  LOGINEMAIL,
  COMPETITIONQUESETION,
  MOBILEREGISTERUSINGMOBILENUMBER,
  NEWTAB,
  OFFERSFORM,
  OPENADMINURL,
  OPENENCASHURL,
  OPENMAILINATORURL,
  OPENAMAZONURL,
  PARTICIPATE,
  QUESTIONNAIRES,
  QUESTIONNAIRESTAB,
  QUESTIONNARIESDELETE,
  QUITBROWSER,
  READEMAILOTPMAILINATOR,
  REGISTERUSINGMOBILENUMBER,
  REGISTRATIONFORM,
  SEARCHCOMPETATION,
  SEARCHCOMPETITION,
  STOREWINDOW,
  SWITCHDRIVER,
  SWITCHWINDOW,
  TAKESCREENSHOT,
  AMAZONITEMADD;
}
