package com.encash.offers.baseframework;

/**
 * This class contain the enum all the keyword. 
 * @author Vinod Kumar R
 *
 */
public enum KeywordType {

  angularWait,
  banner,
  browsertype,
  browserswitch,
  click,
  comment,
  competationform,
  mandatoryquestion,
  mobileparticipate,
  consent,
  closebrowser,
  enteremailotp,
  entertext,
  emailencash,
  encashmenu,
  firebaselogin,
  firebaselogin1,
  gmail,
  gotolink,
  jishitext,
  levels,
  leveltab,
  logoutadmin,
  loginemail,
  competitionquesetion,
  mobileregisterUsingMobileNumber,
  newtab,
  offersform,
  openadminurl,
  openencashurl,
  openmailinatorurl,
  participate,
  questionnaires,
  questionnairestab,
  questionnariesdelete,
  quitbrowser,
  reademailotpmailinator,
  registerUsingMobileNumber,
  registrationform,
  searchcompetation,
  searchcompetition,
  storewindow,
  switchdriver,
  switchwindow,
  takescreenshot,
  verifyattributedvalue,
  verifytext,
  waitforattributedcontain,
  waitForElementInvisible,
  waitForElementPresent,
  waitforelementvisible,
  waitfortexttvisible
}
