version: '2'
services:
    klov:
        image: anshooarora/klov:1.0.1
        container_name: klov
        environment:
            - SPRING_DATA_MONGODB_URI=mongodb://klovdatabase:27017
        ports:
            - 80:80
        links:
            - mongo
    mongo:
        image: mongo
        container_name : klovdatabase
        ports:
            - 27017:27017
    