package com.encash.offers.webdriver;

public enum BrowserExecutionType {
  SYSTEM_CHROME,
  SYSTEM_FIREFOX,
  SYSTEM_OPERA,
  SYSTEM_EDGE,
  SYSTEM_IEXPLORER,
  SYSTEM_CHROMIUM,
  SYSTEM_SAFARI,
  ANDROID_CHROME,
  IOS_SAFARI,
  SYSTEM_MOBILE_EMULATION

}
